language: java
jdk:
 - oraclejdk8
node_js:
 - 7.4.0
sudo: required
dist: trusty
install: true

addons:
  apt:
    sources:
    - george-edison55-precise-backports
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.7
    packages:
    - gcc-5
    - g++-5
    - clang-3.7

compiler: clang-3.7
env: CC=clang-3.7 CXX=clang++-3.7

script:
- mvn -DskipTests -Dspring.profiles.active=dev package -q
- mvn -Dspring.profiles.active=dev test

notifications:
  email:
    recipients:
    - gijs@thehyve.nl
    on_success: change
    on_failure: always
  hipchat:
    rooms:
      secure: SI0Jjvc42mhgjRT9IdRtBUsam0FrHrXjNTr56jD8ZJi/DQN6kxj+lgmXgcRvF6Tsx96vYYIQRHwZjhAET9MeFOPbIbF5PgT5/3V3CrirKcN1vfkUpOnQ20QPnXDYy6b6X2h8kECPyPhMVicUePmQLFqVgF+ycHETGD05Xy7QCgE=
    on_success: change
    on_failure: always

