language: java
jdk:
 - openjdk8
node_js:
 - '10'
sudo: true

install:
- mvn -DskipTests -Dspring.profiles.active=dev package -q

script:
- mvn -Dspring.profiles.active=dev test

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
    - gijs@thehyve.nl
    on_success: change
    on_failure: always
